### ISSUE TITLE
Links Question

### ISSUE THREAD

**Issue by kpb** [spring-projects/spring-restdocs#142]
Trying to use the links functionality. The other snippets work fine on this document.

Link snippet:
```java
links(atomLinks(),
    linkWithRel("some rel").description("Some rel"),
    linkWithRel("other rel").description("Other rel"))
```
Throws a
```bash
org.springframework.restdocs.snippet.ModelCreationException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
 at [Source: java.io.StringReader@5710f755; line: 1, column: 1]
	at org.springframework.restdocs.hypermedia.LinksSnippet.createModel(LinksSnippet.java:90)
	at org.springframework.restdocs.snippet.TemplatedSnippet.document(TemplatedSnippet.java:64)
	at org.springframework.restdocs.mockmvc.RestDocumentationResultHandler.handle(RestDocumentationResultHandler.java:101)
	at org.springframework.test.web.servlet.MockMvc.applyDefaultResultActions(MockMvc.java:176)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:146)
```
The JSON with links looks like:

```javascript
[
    {
        "a": "value",
        "b": "value",
        "links": [
            {
                "rel": "some rel",
                "href": "http://example.com/some"
            },
            {
                "rel": "other rel",
                "href": "http://example.com/other"
            }
        ]
    }
]
```

**Comment by wilkinsona** [comment]
The built-in extract for Atom links expects the payload to be a map. If you want to extract links from an array, you'll need to implement your own extractor that understands the format of the payload.

**Comment by kpb** [comment]
Thanks. The docs say:
```
Atom – links are expected to be in an array named links. 
```
Maybe I'm misreading, but an example or clarification would have saved me some time.

**Comment by wilkinsona** [comment]
Array responses are rather unusual. I'd prefer to keep the documentation concise and cater to the vast majority rather than describing every conceivable edge case. If you want to save yourself some time, you could probably have answered your question in less time than it took to open this issue by looking at the source for `AtomLinkExtractor`.
