### ISSUE TITLE
Getting Error when building my project using SpringRestDocs on Centos

### ISSUE THREAD

**Issue by waqasrajab** [spring-projects/spring-restdocs#184]
Exception is:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':asciidoctor'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- asciidoctor
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
	at RUBY.require(/Users/mr255029/Development/sd-app-gateway/?/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.21/e061b9f399a5e8d5cfcca84d4a6baf879111e83c/jruby-complete-1.7.21.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54)
	at RUBY.(root)(<script>:9)
	at org.asciidoctor.gradle.AsciidoctorTask.instantiateAsciidoctor(AsciidoctorTask.groovy:633)
	at org.asciidoctor.gradle.AsciidoctorTask.processAsciidocSources(AsciidoctorTask.groovy:577)
```

**Comment by waqasrajab** [comment]
BUILD FAILED

My build.gradle looks like following
buildscript {
	ext {
		springBootVersion = '1.3.1.RELEASE'
		 springRestdocsVersion = '1.1.0.BUILD-SNAPSHOT'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		 classpath('io.spring.gradle:dependency-management-plugin:0.5.2.RELEASE')
	}
}

plugins {
    id "org.asciidoctor.convert" version "1.5.3"
}


apply plugin: 'java'
apply plugin: 'spring-boot'
apply plugin: 'eclipse'
apply plugin: 'io.spring.dependency-management'

repositories {
	mavenLocal()
	maven { url 'https://repo.spring.io/libs-snapshot' }
	mavenCentral()
}

group = 'com.tma'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
	mavenLocal()
	maven { url 'https://repo.spring.io/libs-snapshot' }
	mavenCentral()
}

ext {
    snippetsDir = file('build/generated-snippets')   
}


dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('org.springframework.boot:spring-boot-starter-data-jpa')
    compile('com.h2database:h2')
    testCompile('org.springframework.boot:spring-boot-starter-test') 
    testCompile("org.springframework.restdocs:spring-restdocs-mockmvc:$springRestdocsVersion")
}

test {
    outputs.dir snippetsDir
}


asciidoctor {
    attributes 'snippets': snippetsDir
    inputs.dir snippetsDir
    dependsOn test
}

jar {
	dependsOn asciidoctor
	from ("${asciidoctor.outputDir}/html5") {
        into '/public'
    }
}


eclipse {
	classpath {
		 containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
		 containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
	}
}


task wrapper(type: Wrapper) {
	gradleVersion = '2.9'
}

**Comment by wilkinsona** [comment]
This isn't a problem with Spring REST Docs, but with Asciidoctor's Java integration. Unfortunately I haven't encountered this problem before so I don't have any suggestions on how to resolve it. Someone on the [Asciidoctor discussion forum](http://discuss.asciidoctor.org) might be able to help.

If you do ask on the forum, please post a link here to help anyone else who might hit this in the future.

**Comment by waqasrajab** [comment]
I was able to fix the problem by following instructions in the following link

http://mrhaki.blogspot.com/2014/11/awesome-asciidoctor-use-asciidoctor.html

**Comment by wilkinsona** [comment]
I"m glad to hear that you fixed your problem. Thanks for following up. I don't understand why you needed to follow those instructions, though. My understanding is that the `asciidoctor` gem is embedded inside a jar file and is loaded from there. There shouldn't be any need to use the JRuby Gradle plugin to make the `asciidoctor` gem available.

@mojavelinux Can you shed any light on this?

**Comment by waqasrajab** [comment]
Yes, when i run the project on MacOs it works but i had to follow the instructions and change the gradle file to make it work on Centos.

**Comment by mojavelinux** [comment]
> My understanding is that the asciidoctor gem is embedded inside a jar file and is loaded from there.

That is correct. Furthermore, JRuby is configured to only look inside the jar file to resolve gems. However, as the stacktrace provided shows, Asciidoctor is *not* being started in isolation from system gems. Here's the relevant code in AsciidoctorTask:

```java
private void instantiateAsciidoctor() {
    if (gemPaths.size()) {
        asciidoctor = new AsciidoctorProxyImpl(delegate: loadClass(ASCIIDOCTOR_FACTORY_CLASSNAME).create(asGemPath()))
    } else {
        try {
            asciidoctor = new AsciidoctorProxyImpl(delegate: loadClass(ASCIIDOCTOR_FACTORY_CLASSNAME).create(null as String))
        } catch (Exception e) {
            // Asciidoctor < 1.5.1 can't handle a null gemPath, so fallback to default create() method
            asciidoctor = new AsciidoctorProxyImpl(delegate: loadClass(ASCIIDOCTOR_FACTORY_CLASSNAME).create())
        }
    }
}
```

Line 633 is the line inside the catch block. That means that JRuby is resolving gems from the system. That explains the reason for the failure. Since CentOS comes with Ruby installed, it tries to find asciidoctor among the system gems and fails to do so.

What I can't figure out is why it is getting to the catch block. You are clearly using AsciidoctorJ 1.5.3, so it isn't because the method is missing. Something else is failing.

**Comment by mojavelinux** [comment]
For more context about the consequences of using `Asciidoctor.create()` without any arguments, see https://github.com/asciidoctor/asciidoctorj/issues/419. In AsciidoctorJ 1.6.0, we are going to change to make `create()` isolate by default.

**Comment by mojavelinux** [comment]
I'd need a full working project that demonstrates this error on CentOS (ideally in a Docker container) in order to debug any further. I can't emulate the problem on Fedora.

**Comment by wilkinsona** [comment]
@mojavelinux Thank you

**Comment by mojavelinux** [comment]
I am really curious why loading AsciidoctorJ in the try block is failing. I wonder if it is trying to tell us something. Perhaps we should be logging that error.

**Comment by wilkinsona** [comment]
@mojavelinux I just noticed a couple of oddities in the path that's logged:

```
/Users/mr255029/Development/sd-app-gateway/?/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.21/e061b9f399a5e8d5cfcca84d4a6baf879111e83c/jruby-complete-1.7.21.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
```

1. There's a directory named `?` in the path
2. Gradle's cache is relative to the project, rather than being global. It looks like GRADLE_USER_HOME has a non-default value.

I have no reason to believe that either of these is the cause of the problem, but they're both rather unusual and could, perhaps, be a trigger for things heading down an unexpected code path.

**Comment by mojavelinux** [comment]
> There's a directory named ? in the path

Actually, that probably perfectly explains it. JRuby is likely failing to resolve the file path and therefore thinks that no gems are available. We've seen JRuby get confused about paths that are otherwise valid before. The reason is, JRuby has a virtual file system and if there is a bug in that, then it can result it a file read error.

Nice eye!

**Comment by mojavelinux** [comment]
Now the question is, where the is ? coming from. @waqasrajab is this intentional?

**Comment by wilkinsona** [comment]
> Actually, that probably perfectly explains it.

I just tried it. It fails on OS X with a `?` in the path of Gradle's cache:

```
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- asciidoctor
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
	at RUBY.require(/Users/awilkinson/dev/wilkinsona/spring-restdocs/samples/rest-notes-spring-hateoas/?/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.21/e061b9f399a5e8d5cfcca84d4a6baf879111e83c/jruby-complete-1.7.21.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54)
	at RUBY.(root)(<script>:9)
	at org.asciidoctor.gradle.AsciidoctorTask.instantiateAsciidoctor(AsciidoctorTask.groovy:633)
	at org.asciidoctor.gradle.AsciidoctorTask.processAsciidocSources(AsciidoctorTask.groovy:577)
```

**Comment by mojavelinux** [comment]
It seems like the next step is to take this to JRuby if you think that ? should be a valid file folder name. https://github.com/jruby/jruby/issues

**Comment by waqasrajab** [comment]
@mojavelinux 

This isn't intentional, i will do some research on why this directory is being created. Also i am not sure why this ? is being a problem only in Centos and not mac. This is how my gradle build file is looking like right now

 buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		classpath("com.github.jruby-gradle:jruby-gradle-plugin:${jRubyGradlePluginVersion}")
	}
}

plugins {
    id "org.asciidoctor.convert" version "1.5.3"
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'spring-boot'
apply plugin: 'com.github.jruby-gradle.base'

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('org.springframework.boot:spring-boot-starter-data-jpa')
    compile('com.h2database:h2')
    testCompile('org.springframework.boot:spring-boot-starter-test') 
    testCompile("org.springframework.restdocs:spring-restdocs-mockmvc:${springRestDocsVersion}")
    gems "rubygems:asciidoctor:${rubyGemsAsciiDocVersion}" 
}

ext {
    snippetsDir = file('build/generated-snippets')
}

test {
    outputs.dir snippetsDir
}

asciidoctor {
    dependsOn jrubyPrepareGems
    attributes 'snippets': snippetsDir
    inputs.dir snippetsDir
    dependsOn test
    sourceDir 'src/docs/asciidoc'
    outputDir "build/asciidoc"
    gemPath = jrubyPrepareGems.outputDir
}

jar {
	baseName = 'sd-app-gateway'
	dependsOn asciidoctor
	from ("${asciidoctor.outputDir}/html5") {
        into '/public'
    }
}

eclipse {
	classpath {
		 containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
		 containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
	}
}

task jenkins(dependsOn: ['bootRepackage'])

task wrapper(type: Wrapper) {
	gradleVersion = '2.9'
}

**Comment by wilkinsona** [comment]
@waqasrajab The `?` is also a problem on OS X as [shown above](https://github.com/spring-projects/spring-restdocs/issues/184#issuecomment-173148102).

The directory in question is Gradle's home. By default it uses `~/.gradle`. On your CentOS box it appears to be set to `./?/.gradle`. It's typically configured using the `GRADLE_USER_HOME` environment variable. That's what I'd check first.

**Comment by waqasrajab** [comment]
Thank you so much @wilkinsona and @mojavelinux. When i set the GRADLE_USER_HOME it worked, cleaned up my build.gradle :)

**Comment by mojavelinux** [comment]
:guitar:
