### ISSUE TITLE
Can't build source code project in IDE

### ISSUE THREAD

**Issue by psamsotha** [spring-projects/spring-restdocs#185]
Let me just first say that everything builds fine from the command line. So that is not the issue.

I'm trying to build the spring-restdocs project in my IDE, specifically in Netbeans, but I get a build error and project won't import correctly. At first I thought maybe it's a problem with Netbeans (and it's Gradle plugin), but then I tried to import it on STS, and the exact same problem. I can import the project  in STS as an existing workspace project ([as described here](https://github.com/spring-projects/spring-restdocs/blob/master/CONTRIBUTING.md)), but once I try to convert it to a Gradle project, it tries to build and I get the same error. Note that importing as a Gradle project, I get the same error also when I "Build Model".

You can see the complete stacktrace [**here**](https://gist.github.com/psamsotha/3dee2e7946be8c60a37a). Here is a snippet of the root cause

```java
Caused by: java.lang.NullPointerException
	at org.gradle.api.internal.tasks.DefaultTaskDependency.add(DefaultTaskDependency.java:109)
	at org.gradle.api.internal.AbstractTask$11.run(AbstractTask.java:323)
	at org.gradle.api.internal.tasks.TaskMutator.mutate(TaskMutator.java:37)
	at org.gradle.api.internal.AbstractTask.dependsOn(AbstractTask.java:321)
	at org.springframework.restdocs.build.SampleBuildConfigurer.createTask(SampleBuildConfigurer.groovy:55)
	at org.springframework.restdocs.build.SampleBuildConfigurer$createTask.call(Unknown Source)
	at org.springframework.restdocs.build.SamplesExtension.methodMissing(SamplesExtension.groovy:45)
	at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:232)
	at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:127)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:166)
	at org.springframework.restdocs.build.SamplesExtension_Decorated.invokeMethod(Unknown Source)
	at build_acct0eohg2nxae2vfyfgayfcz$_run_closure6.doCall(C:\GitHub\spring-restdocs\build.gradle:157)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_acct0eohg2nxae2vfyfgayfcz.run(C:\GitHub\spring-restdocs\build.gradle:153)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 60 more
```
I've tried a bunch of different things, like grabbing the latest STS, changing Gradle settings in the IDE, using the Gradle wrapper, using the local Gradle Install, but everything fails with the same error.

Then I saw [this commit](https://github.com/spring-projects/spring-restdocs/commit/6443ed177e22a59084a016b1e5809abdf916c3a5), and though it doesn't look related, it got me thinking that maybe it's an OS problem (I am on Windows). This is just a guess. I have no clue really, just a shot in the dark. Can anyone confirm this? Unfortunately I don't have a different OS to test on.

**Comment by wilkinsona** [comment]
Thanks for the detailed problem report.

Gradle's IDE integration is notoriously poor which is why I recommend generating the IDE metadata on the command line and then importing as an existing project. Is a similar approach possible with Netbeans? Perhaps it isn't which is why you're trying to get things working via the IDE integration.

I've just reproduced the problem on OS X so this isn't Windows specific. I'll spend a bit of time seeing if I can work around the problem in a way that isn't too intrusive.

**Comment by wilkinsona** [comment]
This was actually my fault. I'd made a faulty assumption that the working directory would be the root of the Git repo. That's not true when importing the project into an IDE (it's also not true if you use `-project-dir` on the command line. I've fixed this bad assumption and can now import the project's into STS. Hopefully the same will apply to NetBeans.

**Comment by psamsotha** [comment]
It works in Netbeans.. Woohoooo!. Didn't try on STS but I'll take your word for it. Thanks for the quick fix!
