### ISSUE TITLE
Tolerate null entries in the request's parameter map

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-restdocs#199]
The UAA team have some tests where they sometimes put `null` entries in the parameter map. This causes an NPE inside REST Docs. Tolerating `null` parameters will help them. /cc @Priyata25

**Comment by wilkinsona** [comment]
Looking at this some more, it's not clear how a `null` parameter is being specified. `MockHttpServletRequestBuilder.param(String name, String... values)` will throw an exception if the value is `null`.

@Priyata25 can you please describe how you're adding the `null` value into the map of request parameters?

**Comment by Priyata25** [comment]
We are indeed calling something like `.param("scope", null)`. We noticed that this doesn't fail the `notNull` assertion in `addToMultiValueMap` in `MockHttpServletRequestBuilder` (which is called by `MockHttpServletRequestBuilder.param(String name, String... values)`). The null `values` becomes an empty String array instead. /cc @posijon

**Comment by wilkinsona** [comment]
Thanks.

`param` is a varargs method, so passing `null` directly is ambiguous. If you remove the ambiguity by casting to a string array (`param("scope", (String[])null)`) it'll fail:

```java
java.lang.IllegalArgumentException: 'values' is required
	at org.springframework.util.Assert.notNull(Assert.java:112)
	at org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder.addToMultiValueMap(MockHttpServletRequestBuilder.java:697)
	…
```

If the ambiguity is removed by casting to a string (`param("scope", (String)null)`) or by passing in an argument that the compiler knows is a `String` I can reproduce the NPE:

```
java.lang.NullPointerException
	at java.net.URLEncoder.encode(URLEncoder.java:205)
	at org.springframework.restdocs.operation.Parameters.urlEncodeUTF8(Parameters.java:72)
	at org.springframework.restdocs.operation.Parameters.append(Parameters.java:60)
	at org.springframework.restdocs.operation.Parameters.toQueryString(Parameters.java:48)
	at org.springframework.restdocs.curl.CurlRequestSnippet.writeContentUsingParameters(CurlRequestSnippet.java:179)
	at org.springframework.restdocs.curl.CurlRequestSnippet.writeContent(CurlRequestSnippet.java:172)
	at org.springframework.restdocs.curl.CurlRequestSnippet.getOptions(CurlRequestSnippet.java:97)
	at org.springframework.restdocs.curl.CurlRequestSnippet.createModel(CurlRequestSnippet.java:81)
	at org.springframework.restdocs.snippet.TemplatedSnippet.document(TemplatedSnippet.java:64)
	at org.springframework.restdocs.generate.RestDocumentationGenerator.handle(RestDocumentationGenerator.java:192)
	at org.springframework.restdocs.mockmvc.RestDocumentationResultHandler.handle(RestDocumentationResultHandler.java:53)
	at org.springframework.test.web.servlet.MockMvc$1.andDo(MockMvc.java:158)
	at org.springframework.restdocs.mockmvc.MockMvcRestDocumentationIntegrationTests.curlSnippetWithQueryStringOnPost(MockMvcRestDocumentationIntegrationTests.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.restdocs.JUnitRestDocumentation$1.evaluate(JUnitRestDocumentation.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:70)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
