### ISSUE TITLE
Poor diagnostics when attempting to document the fields of a request or response with an empty body

### ISSUE THREAD

**Issue by fwilhe** [spring-projects/spring-restdocs#278]
Is there some way to configure the `ObjectMapper` in `org.springframework.restdocs.payload.JsonContentHandler`? Specifically, is it possible to add modules like to it like so 

```
        objectMapper = new ObjectMapper()
                .registerModule(new Jdk8Module())
                .registerModule(new ParameterNamesModule(JsonCreator.Mode.PROPERTIES))
```

Our problem is that we have immutable Java classes without default constructors and setters. They have one constructor which takes all arguments and getters. The test fails with this stacktrace:

```
org.springframework.restdocs.payload.PayloadHandlingException: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: [B@4a50d04a; line: 1, column: 0]

	at org.springframework.restdocs.payload.JsonContentHandler.readContent(JsonContentHandler.java:84)
	at org.springframework.restdocs.payload.JsonContentHandler.findMissingFields(JsonContentHandler.java:49)
	at org.springframework.restdocs.payload.AbstractFieldsSnippet.validateFieldDocumentation(AbstractFieldsSnippet.java:112)
	at org.springframework.restdocs.payload.AbstractFieldsSnippet.createModel(AbstractFieldsSnippet.java:73)
```

If we could configure the mapper like shown above, this should work.

Looking at the [code](https://github.com/spring-projects/spring-restdocs/blob/6ea6dcf99663edaff1bdb82a64f2086f2fcb3546/spring-restdocs-core/src/main/java/org/springframework/restdocs/payload/JsonContentHandler.java) seems to answer my question. But still, is there a way to configure that I am missing?

**Comment by wilkinsona** [comment]
What you're describing shouldn't be necessary. Jackson's being asked to turn the JSON into a `List` or `Map` so it shouldn't care about your types.

The error is at line 1, column 0. That would suggest to me that the problem is that you've actually returned an empty body, i.e. there's no JSON to be parsed. If that's the case then the error message could certainly improved.

Either way, can you please provide a small sample that illustrates your problem so that I can be sure I'm fixing the right thing?

**Comment by fwilhe** [comment]
Hi @wilkinsona, thanks for your answer. [This](https://github.com/fwilhe/restdocs-issues-278) project should reproduce the issue I have, if I'm not mistaking. Run `./gradlew asciidoctor` and it fails. Expected is that it does not fail.

**Comment by wilkinsona** [comment]
Thanks for the sample. As I suspected, the problem was that you were trying to document the fields of an empty body. That was happening because you weren't including any content in your request.

A secondary problem was that, as you were using `standaloneSetup` Spring MVC was using its default HTTP message converter configuration that didn't know anything about the parameter names module. The easiest way to fix this is to switch to using `webAppContextSetup`.

These changes fix your test:

```diff
diff --git a/src/test/groovy/com/github/fwilhe/ApiDocumentationSpec.groovy b/src/test/groovy/com/github/fwilhe/ApiDocumentationSpec.groovy
index 482956a..354a453 100644
--- a/src/test/groovy/com/github/fwilhe/ApiDocumentationSpec.groovy
+++ b/src/test/groovy/com/github/fwilhe/ApiDocumentationSpec.groovy
@@ -1,22 +1,25 @@
 package com.github.fwilhe
 
-import com.fasterxml.jackson.annotation.JsonCreator
 import com.fasterxml.jackson.databind.ObjectMapper
-import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
-import com.fasterxml.jackson.module.paramnames.ParameterNamesModule
 import org.junit.Rule
+import org.springframework.beans.factory.annotation.Autowired
 import org.springframework.boot.test.SpringApplicationConfiguration
+import org.springframework.http.MediaType
 import org.springframework.restdocs.RestDocumentation
 import org.springframework.test.context.web.WebAppConfiguration
 import org.springframework.test.web.servlet.MockMvc
+import org.springframework.test.web.servlet.result.MockMvcResultMatchers
 import org.springframework.test.web.servlet.setup.MockMvcBuilders
+import org.springframework.web.context.WebApplicationContext
 import spock.lang.Specification
 
 import static org.springframework.restdocs.mockmvc.MockMvcRestDocumentation.document
 import static org.springframework.restdocs.mockmvc.MockMvcRestDocumentation.documentationConfiguration
 import static org.springframework.restdocs.mockmvc.RestDocumentationRequestBuilders.post
 import static org.springframework.restdocs.operation.preprocess.Preprocessors.*
-import static org.springframework.restdocs.payload.PayloadDocumentation.*
+import static org.springframework.restdocs.payload.PayloadDocumentation.fieldWithPath
+import static org.springframework.restdocs.payload.PayloadDocumentation.requestFields
+import static org.springframework.restdocs.payload.PayloadDocumentation.responseFields
 
 @SpringApplicationConfiguration(RestdocsIssues278Application.class)
 @WebAppConfiguration
@@ -27,17 +30,17 @@ class ApiDocumentationSpec extends Specification {
 
     private MockMvc mockMvc
 
+    @Autowired
     private ObjectMapper objectMapper
 
+    @Autowired
+    private WebApplicationContext context
+
     def someResource = new SomeResource()
 
     void setup() {
-        objectMapper = new ObjectMapper()
-                .registerModule(new Jdk8Module())
-                .registerModule(new ParameterNamesModule(JsonCreator.Mode.PROPERTIES))
-
         mockMvc = MockMvcBuilders
-                .standaloneSetup(someResource)
+                .webAppContextSetup(context)
                 .apply(documentationConfiguration(restDocumentation))
                 .build()
     }
@@ -45,9 +48,13 @@ class ApiDocumentationSpec extends Specification {
     def 'Post to Resource'() {
         given:
         def thing = new ImmutableThing("sdf")
+        objectMapper.readValue(objectMapper.writeValueAsString(thing), ImmutableThing.class)
 
         expect:
-        mockMvc.perform(post("/some"))
+        mockMvc.perform(post("/some")
+                        .content(objectMapper.writeValueAsString(thing))
+                        .contentType(MediaType.APPLICATION_JSON))
+                .andExpect(MockMvcResultMatchers.status().isCreated())
                 .andDo(document("post-some",
                 preprocessRequest(prettyPrint()),
                 preprocessResponse(prettyPrint()),
```

I'll use this issue to improve the diagnostics when you attempt to document the fields of request or response with an empty body.

**Comment by fwilhe** [comment]
My bad. The missing body was an error in my sample which is not in our actual application. I updated the sample.

Standard output of the test is

```
2016-07-15 13:25:16.038  WARN 13353 --- [    Test worker] .w.s.m.s.DefaultHandlerExceptionResolver : Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: Could not read document: Can not construct instance of com.github.fwilhe.ImmutableThing: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: java.io.PushbackInputStream@5460b40e; line: 1, column: 2]; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.github.fwilhe.ImmutableThing: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
```

I need to have an instance of my resource because I need to mock a third party component which does remote calls.

**Comment by wilkinsona** [comment]
Your update hasn't addressed this problem:

> A secondary problem was that, as you were using standaloneSetup, Spring MVC was using its default HTTP message converter configuration that didn't know anything about the parameter names module

If you want to use `standaloneSetup` then you'll need to manually configure a message converter with your `ObjectMapper`:

```diff
diff --git a/src/test/groovy/com/github/fwilhe/ApiDocumentationSpec.groovy b/src/test/groovy/com/github/fwilhe/ApiDocumentationSpec.groovy
index f630399..1fe5a6c 100644
--- a/src/test/groovy/com/github/fwilhe/ApiDocumentationSpec.groovy
+++ b/src/test/groovy/com/github/fwilhe/ApiDocumentationSpec.groovy
@@ -7,6 +7,7 @@ import com.fasterxml.jackson.module.paramnames.ParameterNamesModule
 import org.junit.Rule
 import org.springframework.boot.test.SpringApplicationConfiguration
 import org.springframework.http.MediaType
+import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter
 import org.springframework.restdocs.RestDocumentation
 import org.springframework.test.context.web.WebAppConfiguration
 import org.springframework.test.web.servlet.MockMvc
@@ -39,6 +40,7 @@ class ApiDocumentationSpec extends Specification {

         mockMvc = MockMvcBuilders
                 .standaloneSetup(someResource)
+                .setMessageConverters(new MappingJackson2HttpMessageConverter(objectMapper))
                 .apply(documentationConfiguration(restDocumentation))
                 .build()
     }
```

**Comment by fwilhe** [comment]
Thanks, that solves my problem!
