### ISSUE TITLE
Cannot document path parameters when a URI variable is used for a query parameter

### ISSUE THREAD

**Issue by embee1981** [spring-projects/spring-restdocs#285]
I'm currently using spring-restdocs-mockmvc:1.0.2.RELEASE (using some now deprecated features, but trying to get onto 1.1.1 ;-) and having some trouble getting a URL documented that has both path and request parameters e.g. /{hello}/world?foo={bar}

Test code snippet below

```
    @Rule
    public final RestDocumentation restDocumentation = new RestDocumentation("build/generated-snippets");
    @Autowired
    private WebApplicationContext applicationContext;
    private MockMvc mockMvc;
    private RestDocumentationResultHandler document;

    @Before
    public void setUp() {
        document = document("test",
            preprocessRequest(prettyPrint()),
            preprocessResponse(prettyPrint()));

        mockMvc = MockMvcBuilders.webAppContextSetup(applicationContext)
            .apply(documentationConfiguration(this.restDocumentation))
            .alwaysDo(document)
            .build();
    }

    @Test
    public void pathAndRequestParametersPresentInUrl() throws Exception {
        document.snippets(
            pathParameters(parameterWithName("hello").description("some desc")),
            requestParameters(parameterWithName("bar").description("another desc"))
        );
        mockMvc.perform(get("/{hello}/world?foo={bar}", "hello's value", "bar's value"));
    }
```

The exception is as follows

```
org.springframework.restdocs.snippet.SnippetException: Path parameters with the following names were not documented: [bar]

	at org.springframework.restdocs.request.PathParametersSnippet.verificationFailed(PathParametersSnippet.java:121)
	at org.springframework.restdocs.request.AbstractParametersSnippet.verifyParameterDescriptors(AbstractParametersSnippet.java:93)
	at org.springframework.restdocs.request.AbstractParametersSnippet.createModel(AbstractParametersSnippet.java:70)
	at org.springframework.restdocs.request.PathParametersSnippet.createModel(PathParametersSnippet.java:67)
	at org.springframework.restdocs.snippet.TemplatedSnippet.document(TemplatedSnippet.java:64)
	at org.springframework.restdocs.mockmvc.RestDocumentationResultHandler.handle(RestDocumentationResultHandler.java:104)
	at org.springframework.test.web.servlet.MockMvc.applyDefaultResultActions(MockMvc.java:195)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:163)
```

Have I set up the code wrong?

Having a quick look and debug through the code, I think its the NAMES_PATTERN regex in the PathParametersSnippet class is grabbing too many groups and should stop on encountering the "?" before the request parameters are listed. The NAMES_PATTERN regex hasn't changed in the current code base vs 1.0.2 so I think the issue will still exist in the master branch?

**Comment by wilkinsona** [comment]
Thanks for the analysis. I don't think I'd considered that someone may use a variable for a query parameter. You should be able to work around the problem by providing bar's value directly.

**Comment by embee1981** [comment]
Thanks that worked :-)
