### ISSUE TITLE
Issue when documenting constraints & reusing field descriptors

### ISSUE THREAD

**Issue by patrickbray** [spring-projects/spring-restdocs#313]
Hi, 

I have just started using Rest Docs and really like it so far. However I am running into an issue where I am attempting to document the Bean Validation constraints and reuse field descriptors. 

I am basing my implementation on the code linked in the Rest Docs Documentation [ApiDocumentation](https://github.com/spring-projects/spring-restdocs/blob/v1.1.2.RELEASE/samples/rest-notes-spring-hateoas/src/test/java/com/example/notes/ApiDocumentation.java)

```
    private static class ConstrainedFields {

        private final ConstraintDescriptions constraintDescriptions;

        ConstrainedFields(Class<?> input) {
            this.constraintDescriptions = new ConstraintDescriptions(input);
        }

        private FieldDescriptor withPath(String path) {
            return fieldWithPath(path).attributes(key("constraints").value(StringUtils
                    .collectionToDelimitedString(this.constraintDescriptions
                            .descriptionsForProperty(path), ". ")));
        }
    }
```

This is working well when doing something like:

```
final ConstrainedFields fields = new ConstrainedFields(User.class);

requestFields(
	fields.withPath("firstName")
    	.description("The first name of the user"),
    fields.withPath("lastName")
    	.description("The last name of the user")
)
```

However as soon as I attempt to reuse any of these field descriptors something along the lines of: 

```
final ConstrainedFields fields = new ConstrainedFields(User.class);

requestFields(
	fields.withPath("firstName")
    	.description("The first name of the user"))
.and(fields.withPath("lastName")
    	.description("The last name of the user"))
```

I receive the following error:

```
org.springframework.restdocs.mustache.MustacheException$Context: No method or field with name 'constraints' on line 8

	at org.springframework.restdocs.mustache.Template.checkForMissing(Template.java:270)
	at org.springframework.restdocs.mustache.Template.getValue(Template.java:178)
	at org.springframework.restdocs.mustache.Template.getValueOrDefault(Template.java:223)
	at org.springframework.restdocs.mustache.Mustache$VariableSegment.execute(Mustache.java:787)
	at org.springframework.restdocs.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:827)
	at org.springframework.restdocs.mustache.Mustache$SectionSegment.execute(Mustache.java:848)
	at org.springframework.restdocs.mustache.Template.executeSegs(Template.java:114)
	at org.springframework.restdocs.mustache.Template.execute(Template.java:91)
	at org.springframework.restdocs.mustache.Template.execute(Template.java:82)
	at org.springframework.restdocs.templates.mustache.MustacheTemplate.render(MustacheTemplate.java:65)
	at org.springframework.restdocs.snippet.TemplatedSnippet.document(TemplatedSnippet.java:68)
	at org.springframework.restdocs.generate.RestDocumentationGenerator.handle(RestDocumentationGenerator.java:196)
	at org.springframework.restdocs.mockmvc.RestDocumentationResultHandler$1.handle(RestDocumentationResultHandler.java:100)
	at org.springframework.test.web.servlet.MockMvc$1.andDo(MockMvc.java:177)
	at com.example.rest.ExampleDocTest.putDetails(ExampleDocTest.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.restdocs.JUnitRestDocumentation$1.evaluate(JUnitRestDocumentation.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Could these additional attributes be getting stripped as part of the copy on the and or am I doing something wrong?

**Comment by wilkinsona** [comment]
I think you have a different problem to the one that you've described. That error means that your template is using `{{constraints}}` but the object that's in scope has no such attribute.

**Comment by luisdeltoro** [comment]
I'm running into a similar issue trying to combine fields with constraints attribute with method andWithPrefix(String, FieldDescriptor...)
The problem that utility method PayloadDocumentation.applyPathPrefix(String,List<FieldDescriptor>) is not copying the attributed map.
I'll commit a pull request to fix it

**Comment by wilkinsona** [comment]
Thanks, @luisdeltoro. I got things backwards when I read the original description from @patrickbray.

**Comment by wilkinsona** [comment]
Closing in favour of the PR (#314)
