### ISSUE TITLE
Add support for documenting fields in XML payloads

### ISSUE THREAD

**Issue by yohanliyanage** [spring-projects/spring-restdocs#46]
Do you plan to support XML payloads as well?

**Comment by wilkinsona** [comment]
For some aspects of the documentation there's nothing to be done to support XML, for example a cURL request snippet for POSTing an XML payload. On the other hand, the current support for documenting links would require you to write your own `LinkExtractor` as the two built-in extractors are both JSON-specific.

Can you be a bit more specific, what sort of XML payload support are you looking for?

**Comment by yohanliyanage** [comment]
Thanks for the quick response. I am trying to add XML based examples in addition to the JSON based examples to my documentation. I'm not doing HATEOS, so I believe LinkExtractor is not relevant in my case.

When I try to extract response fields from the payload as follows, it seems like the FieldValidator is expecting JSON instead of XML.

Unit Test Code:
	this.mockMvc.perform(get("/api/v1/users").accept(MediaType.APPLICATION_XML))
	    .andExpect(status().isOk())
	    .andDo(document("users-list-example")
	            .withResponseFields(
	                    fieldWithPath("content").description("An array of <<resources-user, User resources>>"),
	                    fieldWithPath("total").description("Total records found"),
	                    fieldWithPath("pageSize").description("Size of a single page"),
	                    fieldWithPath("page").description("Current page number (zero based)"),
	                    fieldWithPath("pages").description("Total number of pages")
	            ));

Test Failure:
    com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
     at [Source: java.io.StringReader@6621a4ef; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1462)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2184)
        at org.springframework.restdocs.payload.FieldValidator.validate(FieldValidator.java:45)
        at org.springframework.restdocs.payload.FieldSnippetResultHandler.handle(FieldSnippetResultHandler.java:72)
        at org.springframework.restdocs.snippet.SnippetWritingResultHandler.handle(SnippetWritingResultHandler.java:51)
        at org.springframework.restdocs.RestDocumentationResultHandler.handle(RestDocumentationResultHandler.java:63)
        at org.springframework.test.web.servlet.MockMvc$1.andDo(MockMvc.java:158)

**Comment by wilkinsona** [comment]
XML is a little more complex than JSON (due to attributes) but it should be possible to do something, particularly as XPath is part of the JDK (I've avoided the use of JSON path as I want to limit Spring REST docs' dependencies as much as possible).
