### ISSUE TITLE
Jackson end-of-input exception when trying to document using withRequestFields

### ISSUE THREAD

**Issue by tommyb82** [spring-projects/spring-restdocs#50]
We are trying to use the new `RestDocumentationResultHandler.withRequestFields` functionality to document our query string parameters, however I am getting the following exception when running the unit test:

com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input at [Source: UNKNOWN; line: 1, column: 1]
at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3110)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2184)
at org.springframework.restdocs.payload.FieldValidator.validate(FieldValidator.java:45)
at org.springframework.restdocs.payload.FieldSnippetResultHandler.handle(FieldSnippetResultHandler.java:72)
at org.springframework.restdocs.snippet.SnippetWritingResultHandler.handle(SnippetWritingResultHandler.java:51)
at org.springframework.restdocs.RestDocumentationResultHandler.handle(RestDocumentationResultHandler.java:63)
at org.springframework.test.web.servlet.MockMvc$1.andDo(MockMvc.java:158)
at *.*.*.api.controllers.landobservations.LandObservationsControllerTest.test 1 resource(LandObservationsControllerTest.groovy:219)

We already use `RestDocumentationResultHandler.withLinks` in the same tests, with no issues. I have tried running only the `withRequestFields` documentor, but get the same result.

I wonder if there is some additional config (perhaps in our jackson ObjectMapper) we need, or if this may be a bug in the new code.. I shall continue to investigate and debug and will update if/when I know more; incidentally the new `RestDocumentationResultHandler.withResponseFields` functionality does not seem to have the same issue, although we have not fully implemented that yet.

Thanks

**Comment by wilkinsona** [comment]
`withRequestFields` will let you document the request body, not the query string parameters. It looks like you trying to document an empty request body (hence the failure being at line 1, column 1 of the input).

Support for documenting query string parameters is #39.

**Comment by tommyb82** [comment]
Ah!  Apologies, yes of course, makes perfect sense.
