### ISSUE TITLE
IllegalStateException when using JUnit 5.3's support for parallel test execution

### ISSUE THREAD

**Issue by Janiczek** [spring-projects/spring-restdocs#520]
JUnit 5.3 M1 allows for a [parallel execution](https://junit.org/junit5/docs/5.3.0-M1/user-guide/index.html#writing-tests-parallel-execution) of tests (if you add `junit.jupiter.execution.parallel.enabled = true` to `src/test/resources/junit-platform.properties`)

Using it with `spring-restdocs` and multiple tests triggers [this error](https://github.com/spring-projects/spring-restdocs/blob/6986cb75a845e24732cb79201aefd8f52c722c89/spring-restdocs-core/src/main/java/org/springframework/restdocs/ManualRestDocumentation.java#L72): `Context already exists. Did you forget to call afterTest()?`

<details>
  <summary>Stacktrace</summary>

```
java.lang.IllegalStateException: Context already exists. Did you forget to call afterTest()?
	at org.springframework.restdocs.ManualRestDocumentation.beforeTest(ManualRestDocumentation.java:72)
	at org.springframework.restdocs.RestDocumentationExtension.beforeEach(RestDocumentationExtension.java:45)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$0(TestMethodTestDescriptor.java:129)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:155)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:128)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:107)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:134)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:128)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:109)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:161)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpStealer(ForkJoinPool.java:1958)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2047)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.joinConcurrentTasksInReverseOrderToEnableWorkStealing(ForkJoinPoolHierarchicalTestExecutorService.java:138)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:112)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:128)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:109)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:161)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
</details>

EDIT: it's also entirely possible this is the bug on JUnit's side, since it seems you call the context-creating and removing methods before and after each test, which seems OK :smile:

**Comment by wilkinsona** [comment]
This appears to be outwith REST Docs' control. I would guess that JUnit's sharing a single instance of REST Docs' extension across multiple tests that are being executed in parallel. If the tests are going to be run in parallel, I'd expect an instance per test, otherwise extensions cannot, easily, be stateful.

@sbrannen Can you please clarify the behaviour of extensions when tests are being run in parallel?

**Comment by sbrannen** [comment]
As an aside, you should be able to use `@ResourceLock` to ensure that your test methods using REST Docs within a single test class do not execute in parallel.

**Comment by Janiczek** [comment]
@sbrannen 

1. I'm basically doing this:

```kotlin
@ExtendWith(RestDocumentationExtension::class)
abstract class ApiTest {

    private lateinit var spec: RequestSpecification

    init {
        RestAssured.reset()
        RestAssured.baseURI = "https://${apiConfig.hostName}"
        RestAssured.port = 443
        RestAssured.basePath = apiConfig.basePath
        RestAssured.authentication = RestAssured.basic(apiConfig.username, apiConfig.pass)
        RestAssured.config = RestAssured
            .config()
            .objectMapperConfig(ObjectMapperConfig().jackson2ObjectMapperFactory { _, _ -> objectMapper })
    }

    @BeforeEach
    fun setUp(restDocumentation: RestDocumentationContextProvider) {
        spec = RequestSpecBuilder()
            .addFilter(
                documentationConfiguration(restDocumentation)
                    .snippets()
                    .withTemplateFormat(markdown())
            )
            .build()
    }

}
```

2. I do have `@TestInstance(PER_CLASS)` on some of my inner test classes because of my usage of `ParameterizedTest` and `MethodSource`. All the other test classes (that do not have this annotation) fail too, though.

3. Sorry, it's proprietary, but I can make minimal examples out of it, if you'd need it.

PS: thanks for `@ResourceLock`! Unfortunately the repo I'm having this error in is all about testing our API, so all the tests are using REST Docs and this would probably nullify the choice to parallelize :)

**Comment by marcphilipp** [comment]
> otherwise extensions cannot, easily, be stateful.

That's exactly right. At least they should not use mutable/stateful instance variables like `RestDocumentationExtension` currently does:

https://github.com/spring-projects/spring-restdocs/blob/aedb9a7babe5ac8b9eb0b0bacc0909fe1b6e3abe/spring-restdocs-core/src/main/java/org/springframework/restdocs/RestDocumentationExtension.java#L34-L51

Instead, the Jupiter API provides a separate concept to store extension state: `ExtensionContext.getStore(Namespace)`. This way JUnit takes care of using the correct store for the current test and the extension does not have to worry about different tests that might even run in parallel.

Here's how that would look for `RestDocumentationExtension`:

```java
public class RestDocumentationExtension implements Extension, BeforeEachCallback,
		AfterEachCallback, RestDocumentationContextProvider, ParameterResolver {

	@Override
	public void beforeEach(ExtensionContext context) throws Exception {
		Class<?> testClass = context.getRequiredTestClass();
		Method testMethod = context.getRequiredTestMethod();
		getDelegate(context).beforeTest(testClass, testMethod.getName());
	}

	@Override
	public void afterEach(ExtensionContext context) throws Exception {
		getDelegate(context).afterTest();
	}

	private ManualRestDocumentation getDelegate(ExtensionContext context) {
		var namespace = Namespace.create(RestDocumentationExtension.class, context.getUniqueId());
		return context.getStore(namespace).getOrComputeIfAbsent(ManualRestDocumentation.class);
	}

	// ...
}
```

@wilkinsona Please let me know if I should submit a PR.

**Comment by sbrannen** [comment]
Thanks for posting the proposed solution using the `Store`, @marcphilipp! 👍 

No need for the extension to implement `Extension` though. I know... it already did, but still.... 😉 

Almost forgot: `var namespace` --> `Namespace namespace` -- Spring REST Docs can't use Java 10.

**Comment by marcphilipp** [comment]
That was just pseudo code anyway... 😉

**Comment by wilkinsona** [comment]
Thanks for the input, @sbrannen and @marcphilipp.

**Comment by Janiczek** [comment]
Thank you all for the hard work!

**Comment by sbrannen** [comment]
> Thanks for the input, @sbrannen and @marcphilipp.

Sure thing!

And thanks for putting in the fix already.

(I left a minor note on the commit)
