### ISSUE TITLE
request parameters cause directory creation errors on Windows

### ISSUE THREAD

**Issue by gurch101** [spring-projects/spring-restdocs#533]
Thank you for creating and maintaining this awesome project!

Right now, url endpoints are used to create the equivalent directory structure so that the documentation for `/api/my-awesome-resource` ends up on the file system in `generated-snippets/api/my-awesome-resource`.

When using request parameters on Windows machines (ie `/api/my-awesome-resource?key=1`), the directory is not created and rest docs throws the following exception:

```
java.lang.IllegalStateException: Failed to create directory 'build\generated-snippets\api\my-awesome-resource?key=1'
              at org.springframework.restdocs.snippet.StandardWriterResolver.createDirectoriesIfNecessary(StandardWriterResolver.java:127)
              at org.springframework.restdocs.snippet.StandardWriterResolver.resolve(StandardWriterResolver.java:91)
```

When I independently attempted to create the same directory using `java.nio`, `mkdirs()` throws the following exception:

```
java.nio.file.InvalidPathException: Illegal char <?> at index 48: build/generated-snippets/api/my-awesome-resource?key=1
              at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
              at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
              at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
              at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
              at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
              at java.nio.file.Paths.get(Paths.java:84)
```

It would be really great if spring rest docs could sanitize the file path before attempted to create the directory. Alternatively, I'd sincerely appreciate some pointers if I am overlooking something or if there is a workaround.

Thanks!

**Comment by wilkinsona** [comment]
> It would be really great if spring rest docs could sanitize the file path before attempted to create the directory.

I guess REST Docs could do that, but that characters that need to be sanitised vary depending on the OS that you are using. 

The path that's used should be under your control as its suffix is whatever you've passed into the `document` method. What I've typically seen is something that's a little more descriptive so you might have `api/my-awesome-resource-single-key` instead. Can you explain why you are passing `api/my-awesome-resource?key=1` into the `document` method?
