### ISSUE TITLE
Problem with WireMockWebTestClient and WebTestClientRestDocumentation in the same test 

### ISSUE THREAD

**Issue by JoaoMFerreira** [spring-projects/spring-restdocs#571]
Hello, I'm trying to use the same combination that's available on RestDocs with Spring Cloud Contracts at this link: [Spring Cloud Contracts With RestDocs](http://cloud-samples.spring.io/spring-cloud-contract-samples/tutorials/rest_docs.html) and I'm facing some issues.
At the section **Rest Docs Producer Tests with Contracts** there's an example that shows this code 
```
@Test
    public void should_grant_a_beer_when_person_is_old_enough() throws Exception {
        PersonToCheck personToCheck = new PersonToCheck(34);
        mockMvc.perform(MockMvcRequestBuilders.post("/check")
                .contentType(MediaType.APPLICATION_JSON)
                .content(json.write(personToCheck).getJson()))
                .andExpect(jsonPath("$.status").value("OK"))
                .andDo(WireMockRestDocs.verify()
                        .jsonPath("$[?(@.age >= 20)]")
                        .contentType(MediaType.valueOf("application/json"))
                        .stub("shouldGrantABeerIfOldEnough"))
                .andDo(MockMvcRestDocumentation.document("shouldGrantABeerIfOldEnough",
                        SpringCloudContractRestDocs.dslContract()));
    }
``` 
If I understand correctly it will generate the contract and the stub with a matchesJsonPath that contains the expression _"$[?(@.amount_ >= 20)]" and that's what I looking for but with the reactive version.
Here's my code in Kotlin.
```
@Test
fun myTest(){
webTestClient.post()
                .uri("/payments")
                .accept(MediaType.APPLICATION_JSON_UTF8)
                .contentType(MediaType.APPLICATION_JSON_UTF8)
                .body(BodyInserters.fromObject(SomeObject))
                .exchange()
                .expectStatus().isCreated
                .expectHeader().contentType(MediaType.APPLICATION_JSON_UTF8)
                .expectBody()
                .jsonPath("$.status_code").isEqualTo("OK")
                .consumeWith(WireMockWebTestClient.verify()
                        .jsonPath("$[?(@.age >= 20)]")
                        .stub("shouldGrantABeerIfOldEnough"))
                .consumeWith(
                        WebTestClientRestDocumentation.document("shouldGrantABeerIfOldEnough",
                                dslContract())
                )
}
```
My code does basically the same but an error occurs when the test is run and NullPointerException is raised in this class WebTestClientRestDocumentationConfigurer.class
I have done some investigation and this point is suspicious ( Lines 81 to 84)
```
static Map<String, Object> retrieveConfiguration(HttpHeaders headers) {
        String requestId = headers.getFirst(WebTestClient.WEBTESTCLIENT_REQUEST_ID);
        return configurations.remove(requestId);
    }
```
since I have 2 consumers in the same Request. It looks like the WebTestClient id is being removed twice and a NullPointerException is raised in the "Configurations" map.
Here the stacktrace:
```
java.lang.NullPointerException
    at java.util.HashMap.putMapEntries(HashMap.java:501)
    at java.util.HashMap.<init>(HashMap.java:490)
    at org.springframework.restdocs.webtestclient.WebTestClientRestDocumentation.retrieveConfiguration(WebTestClientRestDocumentation.java:148)
    at org.springframework.restdocs.webtestclient.WebTestClientRestDocumentation.lambda$document$0(WebTestClientRestDocumentation.java:82)
    at org.springframework.test.web.reactive.server.DefaultWebTestClient$DefaultBodyContentSpec.lambda$consumeWith$2(DefaultWebTestClient.java:496)
    at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:194)
    at org.springframework.test.web.reactive.server.DefaultWebTestClient$DefaultBodyContentSpec.consumeWith(DefaultWebTestClient.java:496)
```

**Comment by wilkinsona** [comment]
Thanks for the report, but you'll need to raise this with the Spring Cloud Contract team. `WebTestClientRestDocumentation.document` should only be called once per test. In your case it's being called twice. You are calling it directly and the call to `WebMockWebTestClient.verify()` also results in it being called.
