### ISSUE TITLE
JsonMappingException when the response is a JSON array

### ISSUE THREAD

**Issue by orfjackal** [spring-projects/spring-restdocs#69]
I'm getting the following exception when using `withResponseFields` on a response which is a JSON array. The test which reproduces this can be seen in [ApiDocumentation.java](https://github.com/HSLdevcom/parkandrideAPI/blob/5c3579785c79db2a7b2a3f736eed228f76ef12b1/application/src/test/java/fi/hsl/parkandride/docs/ApiDocumentation.java#L316-L331) and the controller method called by it is in [FacilityController.java](https://github.com/HSLdevcom/parkandrideAPI/blob/5c3579785c79db2a7b2a3f736eed228f76ef12b1/application/src/main/java/fi/hsl/parkandride/front/FacilityController.java#L118-L124).

```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
 at [Source: java.io.StringReader@4a520f05; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:762)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:758)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:325)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2184)
	at org.springframework.restdocs.payload.FieldValidator.validate(FieldValidator.java:46)
	at org.springframework.restdocs.payload.FieldSnippetResultHandler.handle(FieldSnippetResultHandler.java:69)
	at org.springframework.restdocs.snippet.SnippetWritingResultHandler.handle(SnippetWritingResultHandler.java:51)
	at org.springframework.restdocs.RestDocumentationResultHandler.handle(RestDocumentationResultHandler.java:159)
	at org.springframework.test.web.servlet.MockMvc$1.andDo(MockMvc.java:158)
	at fi.hsl.parkandride.docs.ApiDocumentation.utilizationExample(ApiDocumentation.java:324)
```

**Comment by wilkinsona** [comment]
Thanks for the pointer to the test that was causing the problem. This should now be fixed in the latest snapshots.
