### ISSUE TITLE
Problem documenting response with custom status code with WebTestClient

### ISSUE THREAD

**Issue by LorenzoLuconi** [spring-projects/spring-restdocs#847]
Hi,

The problem should be fixed in version 2.0.4 #639 , but I have the same problem with 2.0.6 version using webtestclient.
The released fix is also valid for webtestaclient?

java.lang.IllegalArgumentException: No matching constant for [210]

	at org.springframework.http.HttpStatus.valueOf(HttpStatus.java:547)
	at org.springframework.mock.http.client.reactive.MockClientHttpResponse.getStatusCode(MockClientHttpResponse.java:71)
	at org.springframework.http.client.reactive.ClientHttpResponseDecorator.getStatusCode(ClientHttpResponseDecorator.java:60)
	at org.springframework.test.web.reactive.server.ExchangeResult.getStatus(ExchangeResult.java:176)
	at org.springframework.restdocs.webtestclient.WebTestClientResponseConverter.convert(WebTestClientResponseConverter.java:39)
	at org.springframework.restdocs.webtestclient.WebTestClientResponseConverter.convert(WebTestClientResponseConverter.java:35)
	at org.springframework.restdocs.generate.RestDocumentationGenerator.handle(RestDocumentationGenerator.java:187)
	at org.springframework.restdocs.webtestclient.WebTestClientRestDocumentation.lambda$document$0(WebTestClientRestDocumentation.java:77)
	at org.springframework.test.web.reactive.server.DefaultWebTestClient$DefaultBodyContentSpec.lambda$consumeWith$3(DefaultWebTestClient.java:709)
	at org.springframework.test.web.reactive.server.ExchangeResult.assertWithDiagnostics(ExchangeResult.java:231)

Thanks,
Lorenzo

**Comment by wilkinsona** [comment]
#639 was specifically for MockMvc as `WebTestClient` didn't provide access to the status in its raw form at that time. Thing should have improved by now so hopefully a similar fix can now be made for `WebTestClient`.
